const data = {
    "2021-02-10": ​​{​​​
        lg1ResultSpread: "Win", 
​​​        lg1ResultTotal: "Lose", 
​​​        lg1SpreadCond: 8.5, 
​​​        lg1SpreadPick: "Home", 
        lg1TotalPick: "Under", 
        llp4ResultSpread: "Lose", 
        llp4ResultTotal: "-", 
        llp4SpreadCond: -8.5, 
        llp4SpreadPick: "Away", 
        llp4TotalPick: "No bet", 
        llpMoneylineAway: -1652.6, 
        llpMoneylineHome: 1652.6, 
        llpScoreAway: 120.8, 
        llpScoreHome: 104.2, 
        llpSpreadAway: -16.7, 
        llpSpreadHome: 16.7, 
        llpTotal: 225, 
        lp4ResultSpread: "-", 
        lp4ResultTotal: "Lose", 
        lp4SpreadCond: "", 
        lp4SpreadPick: "No bet", 
        lp4TotalPick: "Under", 
        lpMoneylineAway: -446.8, 
        lpMoneylineHome: 446.8, 
        lpScoreAway: 105.9, 
        lpScoreHome: 95.9, 
        lpSpreadAway: -10, 
        lpSpreadHome: 10, 
        lpTotal: 201.8, 
        score_away: 122, 
        score_home: 128, 
        slp4ResultSpread: "Lose", 
        slp4ResultTotal: "-", 
        slp4SpreadCond: -8.5, 
        slp4SpreadPick: "Away", 
        slp4TotalPick: "No bet", 
        slpMoneylineAway: -2281.4, 
        slpMoneylineHome: 2281.4, 
        slpScoreAway: 122.6, 
        slpScoreHome: 103.4, 
        slpSpreadAway: -19.2, 
        slpSpreadHome: 19.2, 
        slpTotal: 226, 
        sp4ResultSpread: "-", 
        sp4ResultTotal: "Lose", 
        sp4SpreadCond: "", 
        sp4SpreadPick: "No bet", 
        sp4TotalPick: "Under", 
        spMoneylineAway: -428, 
        spMoneylineHome: 428, 
        spScoreAway: 112.2, 
        spScoreHome: 104.8, 
        spSpreadAway: -7.3, 
        spSpreadHome: 7.3, 
        spTotal: 217, 
        spreadOdds_away: "-112", 
        spreadOdds_home: "-108", 
        spreadOdds_open_away: "-105", 
        spreadOdds_open_home: "-105", 
        spread_away: "-8.5", 
        spread_home: "+8.5", 
        spread_open_away: "-7", 
        spread_open_home: "+7", 
        team_away: "Grizzlies", 
        team_home: "Thunder", 
        total: "222.5", 
        total_open: "221"
    }
}

export {data}